# Generated by Django 3.1.7 on 2021-05-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default='Hero', verbose_name='Hero Name')),
                ('Data', models.JSONField(verbose_name='Hero data in JSON format')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.JSONField(verbose_name='Item data in JSON format')),
            ],
        ),
    ]
